import {NextRequest,NextResponse} from 'next/server'

const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0 Safari/537.36'
const BAD=new Set(['search','feed','im','video','videos','photo','photos','album','albums','clips','clip','wall','login','join','apps','market','groups'])

function decode(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\\u0026/g,'&').replace(/\\u002F/gi,'/').replace(/\\\//g,'/')}
function strip(v:string){return decode(v).replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
async function fetchText(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml','accept-language':'fr-FR,fr;q=0.9,en;q=0.7'},redirect:'follow',cache:'no-store',signal:c.signal});if(!r.ok)return null;return{html:await r.text(),url:r.url}}catch{return null}finally{clearTimeout(t)}}
function title(html:string){const m=html.match(/<meta[^>]+(?:property|name)=["']og:title["'][^>]+content=["']([^"']+)["']/i)||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i);return m?strip(m[1]):''}
function candidates(html:string){const text=decode(html);const out=new Map<string,string>();const add=(raw:string,label='')=>{try{const u=new URL(raw,'https://vk.com');if(!/(^|\.)vk\.com$/i.test(u.hostname))return;const seg=u.pathname.split('/').filter(Boolean)[0]||'';if(!seg||BAD.has(seg.toLowerCase()))return;if(!/^[\w.-]+$/i.test(seg))return;out.set(seg,label||seg)}catch{}};for(const m of text.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi))add(m[1],strip(m[2]));for(const m of text.matchAll(/https?:\/\/(?:m\.)?vk\.com\/([\w.-]+)/gi))add(m[0],m[1]);return [...out].slice(0,30)}

export async function GET(req:NextRequest){const q=(req.nextUrl.searchParams.get('q')||'').trim();if(!q)return NextResponse.json({error:'q manquant'},{status:400});const queries=[`site:vk.com ${q}`,`site:vk.com/public ${q}`,`site:vk.com/club ${q}`];const urls=queries.flatMap(x=>[`https://search.brave.com/search?q=${encodeURIComponent(x)}&source=web`,`https://www.bing.com/search?q=${encodeURIComponent(x)}&count=30&adlt=off`,`https://yandex.com/search/?text=${encodeURIComponent(x)}`]);const pages=(await Promise.all(urls.map(fetchText))).filter(Boolean) as {html:string;url:string}[];const raw=new Map<string,string>();for(const p of pages)for(const [h,l] of candidates(p.html))raw.set(h,l);const enriched=[] as any[];for(const [handle,label] of [...raw].slice(0,18)){const f=await fetchText(`https://vk.com/${handle}`);enriched.push({handle,url:`https://vk.com/${handle}`,label,title:f?title(f.html):''})}const words=q.toLowerCase().split(/\s+/).filter(x=>x.length>2);enriched.sort((a,b)=>{const sa=words.filter(w=>(a.title+' '+a.label+' '+a.handle).toLowerCase().includes(w)).length;const sb=words.filter(w=>(b.title+' '+b.label+' '+b.handle).toLowerCase().includes(w)).length;return sb-sa});return NextResponse.json({query:q,candidates:enriched.slice(0,12)},{headers:{'Cache-Control':'no-store'}})}
