import {NextRequest,NextResponse} from 'next/server'

const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0 Safari/537.36'
const BAD=new Set(['search','feed','im','video','videos','photo','photos','album','albums','clips','clip','wall','login','join','apps','market','groups','settings','ask','images','news','maps','goggles','copilotsearch'])

function decode(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\\u0026/g,'&').replace(/\\u002F/gi,'/').replace(/\\\//g,'/')}
function strip(v:string){return decode(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
async function fetchText(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),8000);try{const r=await fetch(url,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml','accept-language':'fr-FR,fr;q=0.9,en;q=0.7'},redirect:'follow',cache:'no-store',signal:c.signal});if(!r.ok)return null;return{html:await r.text(),url:r.url}}catch{return null}finally{clearTimeout(t)}}
function pageTitle(html:string){const m=html.match(/<meta[^>]+(?:property|name)=["']og:title["'][^>]+content=["']([^"']+)["']/i)||html.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||html.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);return m?strip(m[1]):''}
function addCandidate(out:Map<string,{label:string;context:string}>,raw:string,label:string,context:string){try{const u=new URL(decode(raw),'https://vk.com');if(!/(^|\.)vk\.com$/i.test(u.hostname))return;const seg=u.pathname.split('/').filter(Boolean)[0]||'';if(!seg||BAD.has(seg.toLowerCase())||!/^[\w.-]+$/i.test(seg))return;const prev=out.get(seg);const next={label:strip(label)||seg,context:strip(context).slice(0,500)};if(!prev||next.context.length>prev.context.length)out.set(seg,next)}catch{}}
function candidates(html:string){const text=decode(html);const out=new Map<string,{label:string;context:string}>();for(const m of text.matchAll(/<a\b[^>]*href=["']([^"']+)["'][^>]*>([\s\S]*?)<\/a>/gi)){const idx=m.index||0;addCandidate(out,m[1],m[2],text.slice(Math.max(0,idx-350),idx+700))}for(const m of text.matchAll(/https?:\/\/(?:m\.)?vk\.com\/([\w.-]+)/gi)){const idx=m.index||0;addCandidate(out,m[0],m[1],text.slice(Math.max(0,idx-300),idx+550))}return [...out]}

export async function GET(req:NextRequest){const q=(req.nextUrl.searchParams.get('q')||'').trim();if(!q)return NextResponse.json({error:'q manquant'},{status:400});const variants=[q,q.replace(/Phil/gi,'fil'),q.replace(/fil/gi,'Phil')];const queries=[...new Set(variants.flatMap(v=>[`site:vk.com ${v}`,`site:vk.com/public ${v}`,`site:vk.com/club ${v}`,`site:vk.com ${v} bande dessinée`]))];const urls=queries.flatMap(x=>[`https://search.brave.com/search?q=${encodeURIComponent(x)}&source=web`,`https://www.bing.com/search?q=${encodeURIComponent(x)}&count=30&adlt=off`,`https://yandex.com/search/?text=${encodeURIComponent(x)}`]);const pages=(await Promise.all(urls.slice(0,18).map(fetchText))).filter(Boolean) as {html:string;url:string}[];const raw=new Map<string,{label:string;context:string}>();for(const p of pages)for(const [h,v] of candidates(p.html)){const prev=raw.get(h);if(!prev||v.context.length>prev.context.length)raw.set(h,v)}const enriched=[] as any[];for(const [handle,meta] of [...raw].slice(0,24)){const [desk,mob]=await Promise.all([fetchText(`https://vk.com/${handle}`),fetchText(`https://m.vk.com/${handle}`)]);enriched.push({handle,url:`https://vk.com/${handle}`,label:meta.label,context:meta.context,titleDesktop:desk?pageTitle(desk.html):'',titleMobile:mob?pageTitle(mob.html):''})}const words=[...new Set(variants.join(' ').toLowerCase().split(/\s+/).filter(x=>x.length>2))];enriched.sort((a,b)=>{const score=(x:any)=>words.filter(w=>(x.titleDesktop+' '+x.titleMobile+' '+x.label+' '+x.context+' '+x.handle).toLowerCase().includes(w)).length;return score(b)-score(a)});return NextResponse.json({query:q,candidates:enriched.slice(0,15)},{headers:{'Cache-Control':'no-store'}})}
