'use client'

import {useEffect,useMemo,useRef,useState} from 'react'

type Format='pdf'|'epub'
type Book={topicId:number;title:string;description:string;genres:string[];publication:string|null;tomes:string|null;origin:string|null;language:string|null;sourceUrl:string;integratedAt:string|null;integrationOrder:number;kind:'bd'|'livre';formatHint:Format|null}
type Detail={topicId:number;format:Format|null;fileName:string|null;downloadCount:number|null;preview:string|null;authorizedUrl:string|null;fileDetected:boolean;language:string|null;sourceUrl:string;rights:'verified-public'|'unverified'}
type DetailState=Detail|'loading'|null
const BATCH=8

function uniqBooks(items:Book[]){const m=new Map<number,Book>();for(const x of items)m.set(x.topicId,x);return [...m.values()]}
function labelDate(b:Book){if(b.integratedAt)return new Intl.DateTimeFormat('fr-FR',{day:'2-digit',month:'2-digit',year:'numeric'}).format(new Date(b.integratedAt));return `ordre VK #${b.integrationOrder}`}
function actualKind(b:Book,d:DetailState){if(d&&d!=='loading'&&d.format==='epub')return'livre';if(d&&d!=='loading'&&d.format==='pdf')return'bd';return b.kind}
function actualFormat(b:Book,d:DetailState){return d&&d!=='loading'?d.format:b.formatHint}

export default function BooksPanel({query}:{query:string}){
 const[books,setBooks]=useState<Book[]>([]);const[categories,setCategories]=useState<string[]>([]);const[category,setCategory]=useState('');const[type,setType]=useState<'all'|'bd'|'livre'>('all');const[nextPage,setNextPage]=useState<number|null>(0);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[shown,setShown]=useState(BATCH);const[details,setDetails]=useState<Record<number,DetailState>>({});const sentinel=useRef<HTMLDivElement|null>(null);const loadingRef=useRef(false)
 async function load(next:number,append:boolean){if(loadingRef.current)return;loadingRef.current=true;setLoading(true);setError('');try{const r=await fetch(`/api/books?page=${next}`,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Catalogue indisponible');const incoming:Array<Book>=Array.isArray(d.books)?d.books:[];setBooks(prev=>uniqBooks(append?[...prev,...incoming]:incoming));setCategories(prev=>[...new Set([...(append?prev:[]),...(Array.isArray(d.categories)?d.categories:[])])].sort((a,b)=>a.localeCompare(b,'fr')));const candidate=typeof d.nextPage==='number'?d.nextPage:null;setNextPage(candidate!==null&&candidate<=next?next+1:candidate);if(append)setShown(v=>v+BATCH)}catch(e){setError(e instanceof Error?e.message:'Catalogue indisponible')}finally{loadingRef.current=false;setLoading(false)}}
 async function enrich(topicId:number){if(details[topicId]!==undefined)return;setDetails(prev=>({...prev,[topicId]:'loading'}));try{const r=await fetch(`/api/books/detail?topicId=${topicId}`,{cache:'force-cache'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Détail indisponible');setDetails(prev=>({...prev,[topicId]:d as Detail}))}catch{setDetails(prev=>({...prev,[topicId]:null}))}}
 useEffect(()=>{void load(0,false)},[])
 useEffect(()=>{setShown(BATCH)},[category,type,query])
 const ranked=useMemo(()=>{const q=query.trim().toLocaleLowerCase('fr');const filtered=books.filter(b=>{const d=details[b.topicId];const k=actualKind(b,d);return(!category||b.genres.some(g=>g===category))&&(type==='all'||k===type)&&(!q||(b.title+' '+b.description+' '+b.genres.join(' ')).toLocaleLowerCase('fr').includes(q))});return [...filtered].sort((a,b)=>{const da=details[a.topicId],db=details[b.topicId];const ca=da&&da!=='loading'?da.downloadCount:null,cb=db&&db!=='loading'?db.downloadCount:null;if(ca!==null||cb!==null){if(ca===null)return 1;if(cb===null)return-1;if(cb!==ca)return cb-ca}return b.integrationOrder-a.integrationOrder})},[books,category,type,query,details])
 const visible=ranked.slice(0,shown)
 useEffect(()=>{const el=sentinel.current;if(!el)return;const io=new IntersectionObserver(entries=>{if(!entries[0]?.isIntersecting||loadingRef.current)return;if(shown<ranked.length){setShown(v=>Math.min(ranked.length,v+BATCH));return}if(nextPage!==null)void load(nextPage,true)},{rootMargin:'900px 0px'});io.observe(el);return()=>io.disconnect()},[shown,ranked.length,nextPage])
 return <section className="booksWrap">
  <div className="booksHead"><div><strong>Au Phil Des Bulles</strong><small>Français · PDF pour BD · EPUB pour livres · tri téléchargements si VK l’expose</small></div><div className="bookFilters"><select value={type} onChange={e=>setType(e.target.value as 'all'|'bd'|'livre')}><option value="all">BD + Livres</option><option value="bd">BD / PDF</option><option value="livre">Livres / EPUB</option></select><select value={category} onChange={e=>setCategory(e.target.value)}><option value="">Toutes les classifications</option>{categories.map(c=><option key={c} value={c}>{c}</option>)}</select></div></div>
  <div className="booksNotice">Chaque carte est enrichie progressivement depuis sa discussion VK : langue française, format détecté, aperçu indexé et compteur de téléchargements lorsqu’il est public. Les fichiers dont les droits de diffusion ne peuvent pas être vérifiés restent signalés sans lien direct ; la discussion VK demeure accessible.</div>
  {error&&<div className="error">{error}</div>}
  <div className="bookGrid">{visible.map(b=><BookCard key={b.topicId} book={b} detail={details[b.topicId]} onNeedDetail={()=>void enrich(b.topicId)}/>)}</div>
  {!loading&&!ranked.length&&<div className="booksEmpty">Aucun résultat français pour ce filtre.</div>}
  <div ref={sentinel} className={`booksSentinel ${loading?'loading':''}`}><span/>{loading&&<small>Indexation progressive…</small>}</div>
 </section>
}

function BookCard({book,detail,onNeedDetail}:{book:Book;detail:DetailState;onNeedDetail:()=>void}){useEffect(()=>{onNeedDetail()},[book.topicId]);const d=detail&&detail!=='loading'?detail:null;const format=actualFormat(book,detail);const kind=actualKind(book,detail);const fileLabel=format?format.toUpperCase():d?.fileDetected?'DOC':'—';const count=d?.downloadCount;return <article className="bookCard"><div className="bookPreview">{d?.preview?<img src={d.preview} alt={`Aperçu de ${book.title}`} loading="lazy"/>:<div className="bookPreviewFallback"><span>AU PHIL DES BULLES</span><b>{book.title}</b><small>{detail==='loading'?'Recherche de la première page…':'Aperçu non indexé'}</small></div>}<div className="bookPreviewBadges"><span>{kind==='livre'?'LIVRE':'BD'}</span><em>{fileLabel}</em></div></div><div className="bookBody"><div className="bookTop"><small>{labelDate(book)}</small><small className={count!==null&&count!==undefined?'downloads known':'downloads'}>{count!==null&&count!==undefined?`${new Intl.NumberFormat('fr-FR').format(count)} téléchargements`:'Téléchargements non exposés'}</small></div><h2>{book.title}</h2><div className="bookTags">{book.genres.map(g=><span key={g}>{g}</span>)}</div><dl>{book.publication&&<><dt>Parution</dt><dd>{book.publication}</dd></>}{book.tomes&&<><dt>Tomes</dt><dd>{book.tomes}</dd></>}{book.origin&&<><dt>Origine</dt><dd>{book.origin}</dd></>}<dt>Langue</dt><dd>{d?.language||book.language||'Français'}</dd>{d?.fileName&&<><dt>Fichier</dt><dd>{d.fileName}</dd></>}</dl><div className="bookActions">{d?.authorizedUrl&&<button className="fileAction" onClick={()=>window.open(d.authorizedUrl!,'_blank','noopener,noreferrer')}>Ouvrir {format?.toUpperCase()} ↗</button>}<button onClick={()=>window.open(book.sourceUrl,'_blank','noopener,noreferrer')}>Discussion VK ↗</button></div></div></article>}
