'use client'

import Hls from 'hls.js'
import {FormEvent,useEffect,useMemo,useRef,useState} from 'react'

type Photo={thumb:string;fullsize:string;alt:string}
type Video={playlist:string|null;player:string|null;thumbnail:string|null;alt:string;aspectRatio:{width:number;height:number}|null}
type Post={uri:string;cid:string;text:string;createdAt:string;author:{handle:string;displayName:string;avatar:string|null};images?:Photo[];video?:Video;likeCount:number;repostCount:number}
type Mode='search'|'videos'|'accounts'
type Media={key:string;kind:'image'|'video';src:string|null;player:string|null;poster:string|null;author:string;ratio?:{width:number;height:number}|null}
const ACCOUNTS_KEY='visual-search-2-accounts';const MAX_ACCOUNTS=20
function shuffle<T>(a:T[]){const c=[...a];for(let i=c.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[c[i],c[j]]=[c[j],c[i]]}return c}
function unique(posts:Post[]){const s=new Set<string>();return posts.filter(p=>!s.has(p.uri)&&(s.add(p.uri),true))}
function mediaOf(posts:Post[],mode:Mode):Media[]{const out:Media[]=[];for(const p of posts){if(mode!=='videos')for(let i=0;i<(p.images||[]).length;i++){const x=p.images![i];out.push({key:`${p.uri}:i${i}`,kind:'image',src:x.fullsize,player:null,poster:x.thumb,author:p.author.handle})}if(mode!=='search'&&p.video){const v=p.video;out.push({key:`${p.uri}:v`,kind:'video',src:v.playlist,player:v.player,poster:v.thumbnail,author:p.author.handle,ratio:v.aspectRatio})}}return out}
function cleanAccount(v:string){return v.trim().replace(/^@+/,'').replace(/^https?:\/\/(?:m\.)?vk\.com\//i,'').split(/[?#/]/)[0]}

function VideoTile({m,onOpen}:{m:Media;onOpen:()=>void}){const ref=useRef<HTMLVideoElement|null>(null);const hls=useRef<Hls|null>(null);const[started,setStarted]=useState(false);useEffect(()=>{if(!started||!m.src||!ref.current)return;const el=ref.current;if(/\.m3u8(?:\?|$)/i.test(m.src)&&!el.canPlayType('application/vnd.apple.mpegurl')&&Hls.isSupported()){const h=new Hls({enableWorker:true,maxBufferLength:18,backBufferLength:12});hls.current=h;h.loadSource(m.src);h.attachMedia(el);h.on(Hls.Events.MANIFEST_PARSED,()=>void el.play().catch(()=>{}));return()=>{h.destroy();hls.current=null}}el.src=m.src;void el.play().catch(()=>{})},[started,m.src]);return <article className="videoCard" style={{aspectRatio:m.ratio?`${m.ratio.width}/${m.ratio.height}`:'9/16'}} onDoubleClick={onOpen}>{m.poster&&!started&&<img src={m.poster} alt=""/>}{m.src?<video ref={ref} controls={started} playsInline preload="none" onClick={()=>setStarted(true)}/>:m.player?<iframe src={m.player} allow="autoplay; encrypted-media; fullscreen; picture-in-picture" allowFullScreen/>:null}{!started&&m.src&&<button className="play" onClick={()=>setStarted(true)} aria-label="Lire"><span/></button>}<button className="expand" onClick={onOpen} aria-label="Plein écran">↗</button></article>}

export default function Home(){
 const[mode,setMode]=useState<Mode>('search');const[query,setQuery]=useState('');const[accounts,setAccounts]=useState<string[]>([]);const[posts,setPosts]=useState<Post[]>([]);const[cursor,setCursor]=useState<string|null>(null);const[loading,setLoading]=useState(false);const[error,setError]=useState('');const[batch,setBatch]=useState(0);const[age,setAge]=useState(false);const[viewer,setViewer]=useState<number|null>(null);const sentinel=useRef<HTMLDivElement|null>(null);const loadingRef=useRef(false)
 useEffect(()=>{setAge(localStorage.getItem('visual-search-2-age')==='yes');try{const a=JSON.parse(localStorage.getItem(ACCOUNTS_KEY)||'[]');if(Array.isArray(a))setAccounts(a.map(cleanAccount).filter(Boolean).slice(0,MAX_ACCOUNTS))}catch{}},[])
 const media=useMemo(()=>mediaOf(posts,mode),[posts,mode]);const current=viewer===null?null:media[viewer]||null
 function saveAccounts(a:string[]){const n=[...new Set(a.map(cleanAccount).filter(Boolean))].slice(0,MAX_ACCOUNTS);setAccounts(n);localStorage.setItem(ACCOUNTS_KEY,JSON.stringify(n))}
 async function load(opts:{append?:boolean;discover?:boolean;mode?:Mode;q?:string}={}){if(loadingRef.current)return;const md=opts.mode||mode;const append=!!opts.append;const discover=!!opts.discover;const q=(opts.q??query).trim();if(md==='accounts'&&!accounts.length&&!q)return;loadingRef.current=true;setLoading(true);setError('');try{let url='';if(discover){url=`/api/discover?kind=${md==='videos'?'video':'image'}&batch=${batch+1}`;setBatch(v=>v+1)}else if(md==='accounts'){const aq=(q?q.split(/[\s,;]+/).map(cleanAccount).filter(Boolean):accounts).map(a=>`@${a}`).join(',');url=`/api/account-feed?q=${encodeURIComponent(aq)}${append&&cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`}else{url=`${md==='videos'?'/api/videos':'/api/search'}?q=${encodeURIComponent(q)}${append&&cursor?`&cursor=${encodeURIComponent(cursor)}`:''}`}
 const r=await fetch(url,{cache:'no-store'});const d=await r.json();if(!r.ok)throw new Error(d.error||'Erreur');const incoming=unique(d.posts||[]);setPosts(prev=>append?unique([...prev,...incoming]):(discover?shuffle(incoming):incoming));setCursor(d.cursor||null)}catch(e){setError(e instanceof Error?e.message:'Erreur')}finally{loadingRef.current=false;setLoading(false)}}
 useEffect(()=>{if(mode==='videos'&&!posts.length)void load({discover:true,mode:'videos'});if(mode==='accounts'&&accounts.length&&!posts.length)void load({mode:'accounts'})},[mode])
 useEffect(()=>{const el=sentinel.current;if(!el||!posts.length)return;const io=new IntersectionObserver(es=>{if(!es[0]?.isIntersecting||loadingRef.current)return;if(mode==='accounts'){if(cursor)void load({append:true,mode:'accounts'})}else if(query.trim()){if(cursor)void load({append:true})}else void load({append:true,discover:true,mode})},{rootMargin:'1200px 0px'});io.observe(el);return()=>io.disconnect()},[posts.length,cursor,mode,query,batch,accounts.join(',')])
 function submit(e:FormEvent){e.preventDefault();if(mode==='accounts'){const a=cleanAccount(query);if(!a)return;const next=[...accounts,a];saveAccounts(next);setQuery('');setPosts([]);setTimeout(()=>void load({mode:'accounts',q:next.join(',')}),0);return}if(query.trim()){setPosts([]);void load({q:query})}}
 function switchMode(m:Mode){setMode(m);setPosts([]);setCursor(null);setError('');setQuery('');setViewer(null)}
 function addFlow(author:string){const a=cleanAccount(author);if(a&&!accounts.includes(a))saveAccounts([...accounts,a])}
 function moveViewer(d:number){if(viewer===null)return;setViewer(Math.max(0,Math.min(media.length-1,viewer+d)))}
 return <main>{!age&&<div className="gate"><div className="gateCard"><b>18+</b><h1>Accès réservé aux adultes</h1><p>Je certifie avoir au moins 18 ans et être autorisé à consulter ce contenu dans mon pays.</p><button onClick={()=>{localStorage.setItem('visual-search-2-age','yes');setAge(true)}}>J’ai 18 ans ou plus</button></div></div>}
 <header className="hero"><div className="brand"><span className="mark">18+</span><strong>FLOW</strong><small>VISUAL SEARCH</small></div><nav>
  <button className={mode==='search'?'active':''} onClick={()=>switchMode('search')} aria-label="Photos"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2.5"/><circle cx="8.5" cy="9.5" r="1.6"/><path d="m5.5 16 4.2-4.1 3.2 3 2.2-2.1 3.4 3.2"/></svg></button>
  <button className={mode==='videos'?'active':''} onClick={()=>switchMode('videos')} aria-label="Vidéos"><svg viewBox="0 0 24 24"><rect x="3" y="5" width="18" height="14" rx="2.5"/><path d="M7 5v14M17 5v14M3.5 9h3.2M3.5 15h3.2M17.3 9h3.2M17.3 15h3.2"/><path d="m10 9 5 3-5 3Z"/></svg></button>
  <button className={mode==='accounts'?'active':''} onClick={()=>switchMode('accounts')} aria-label="Comptes"><svg viewBox="0 0 24 24"><path d="M12 11.7C10.4 7.5 7.6 5.3 4.2 5.1c-.2 3.6 1.3 6.2 4.1 7.4-2.6.8-4 2.9-4.1 6.2 3.7-.1 6.3-1.8 7.8-5.2 1.5 3.4 4.1 5.1 7.8 5.2-.1-3.3-1.5-5.4-4.1-6.2 2.8-1.2 4.3-3.8 4.1-7.4-3.4.2-6.2 2.4-7.8 6.6Z"/></svg></button>
 </nav><form onSubmit={submit}><input value={query} onChange={e=>setQuery(e.target.value)} placeholder={mode==='accounts'?'@compte ou vk.com/compte…':'Rechercher…'}/><button disabled={loading||!query.trim()} aria-label="Lancer">⌕</button></form>{mode==='accounts'&&accounts.length>0&&<div className="chips">{accounts.map(a=><button key={a} onClick={()=>{saveAccounts(accounts.filter(x=>x!==a));setPosts([])}}>@{a} ×</button>)}</div>}</header>
 {error&&<div className="error">{error}</div>}
 <section className={mode==='videos'?'videoGrid':mode==='accounts'?'mixedGrid':'grid'}>{media.map((m,i)=>m.kind==='image'?<article key={m.key} className="imageCard" onClick={()=>setViewer(i)}><img src={m.poster||m.src||''} alt="" loading="lazy"/></article>:<VideoTile key={m.key} m={m} onOpen={()=>setViewer(i)}/>)}</section>
 {posts.length>0&&<div ref={sentinel} className={`sentinel ${loading?'loading':''}`}><span/></div>}
 {current&&<div className="viewer" onTouchStart={e=>{(e.currentTarget as any)._y=e.touches[0].clientY}} onTouchEnd={e=>{const y=(e.currentTarget as any)._y;const dy=e.changedTouches[0].clientY-y;if(Math.abs(dy)>50)moveViewer(dy<0?1:-1)}}>{current.kind==='image'?<img src={current.src||''} alt=""/>:current.src?<FullscreenVideo m={current} onEnded={()=>moveViewer(1)}/>:current.player?<iframe src={current.player} allow="autoplay; encrypted-media; fullscreen; picture-in-picture" allowFullScreen/>:null}<button className="close" onClick={()=>setViewer(null)}>×</button><button className="prev" onClick={()=>moveViewer(-1)}>‹</button><button className="next" onClick={()=>moveViewer(1)}>›</button><button className="flow" onClick={()=>addFlow(current.author)}><span>♦</span> flow</button></div>}
 </main>}

function FullscreenVideo({m,onEnded}:{m:Media;onEnded:()=>void}){const ref=useRef<HTMLVideoElement|null>(null);useEffect(()=>{const el=ref.current;if(!el||!m.src)return;if(/\.m3u8(?:\?|$)/i.test(m.src)&&!el.canPlayType('application/vnd.apple.mpegurl')&&Hls.isSupported()){const h=new Hls({enableWorker:true,maxBufferLength:14});h.loadSource(m.src);h.attachMedia(el);h.on(Hls.Events.MANIFEST_PARSED,()=>void el.play().catch(()=>{}));return()=>h.destroy()}el.src=m.src;void el.play().catch(()=>{})},[m.src]);return <video ref={ref} controls autoPlay muted playsInline poster={m.poster||undefined} onEnded={onEnded}/>} 
