type AnyPost=Record<string,any>

function tokens(q:string){return [...new Set(q.toLocaleLowerCase('fr').split(/[^\p{L}\p{N}_-]+/u).map(x=>x.trim()).filter(x=>x.length>1))]}
function dims(url:string){try{const u=new URL(url);const pairs:string[]=[];for(const k of ['size','cs']){const v=u.searchParams.get(k);if(v)pairs.push(v)}const as=u.searchParams.get('as');if(as)pairs.push(...as.split(','));const crop=u.searchParams.get('crop');if(crop){const p=crop.split(',').map(Number);if(p.length>=4&&p[2]>0&&p[3]>0)pairs.push(`${p[2]}x${p[3]}`)}let best:{w:number;h:number}|null=null;for(const p of pairs){const m=p.match(/(\d{2,5})x(\d{2,5})/);if(!m)continue;const w=Number(m[1]),h=Number(m[2]);if(!best||w*h>best.w*best.h)best={w,h}}return best}catch{return null}}
function malformed(url:string){const lower=url.toLowerCase();const a=lower.indexOf('https://',8),b=lower.indexOf('http://',8);return a>=0||b>=0}
function canonical(url:string){try{const u=new URL(url);return `${u.hostname.toLowerCase()}${u.pathname}`}catch{return url}}
function textOf(p:AnyPost){const img=Array.isArray(p?.images)?p.images[0]:null;return `${p?.text||''} ${p?.author?.handle||''} ${p?.author?.displayName||''} ${img?.alt||''} ${p?.uri||''}`.toLocaleLowerCase('fr')}

export function screenPhotoResult(result:any,q:string){
 const input:Array<AnyPost>=Array.isArray(result?.posts)?result.posts:[];const qs=tokens(q);const seen=new Set<string>();const ranked:{p:AnyPost;score:number}[]=[]
 for(const p of input){const img=Array.isArray(p?.images)?p.images[0]:null;const url=String(img?.fullsize||img?.thumb||'');if(!url)continue;let u:URL;try{u=new URL(url)}catch{continue}if(!/^https:$/.test(u.protocol)||malformed(url))continue;const s=(u.pathname+u.search).toLowerCase();if(/type=cover_group|type=video_thumb|[?&]ava=1(?:&|$)|\/video\//i.test(s))continue;const key=canonical(url);if(seen.has(key))continue;const d=dims(url);if(d&&Math.min(d.w,d.h)<120)continue;let score=0;if(/^https?:\/\/(?:m\.)?vk\.com\/photo/i.test(String(p?.uri||'')))score+=8;if(/\/s\/v1\/ig\d?\//i.test(u.pathname)||/\/impg\//i.test(u.pathname)||/\/impf\//i.test(u.pathname))score+=3;if(/type=album/i.test(s))score+=2;if(d){const area=d.w*d.h;if(area>=900000)score+=6;else if(area>=450000)score+=5;else if(area>=220000)score+=4;else if(area>=100000)score+=2;else score-=1;const ratio=d.w/d.h;if(ratio>=.55&&ratio<=1.6)score+=2;if(ratio<.38||ratio>2.4)score-=5}if(/[?&]blur=/i.test(s))score-=2;const txt=textOf(p);for(const t of qs)if(txt.includes(t))score+=1;seen.add(key);ranked.push({p,score})}
 ranked.sort((a,b)=>b.score-a.score);const posts=ranked.slice(0,36).map(x=>x.p);return{...result,posts,screening:{strategy:'keyword-quality-v1',before:input.length,after:posts.length}}
}

export function screenVideoResult(result:any,q:string){
 const input:Array<AnyPost>=Array.isArray(result?.posts)?result.posts:[];const qs=tokens(q);const ranked=input.map((p,i)=>{const v=p?.video||{};let score=0;if(v.playlist)score+=10;else if(v.player)score+=8;const page=String(v.pageUrl||p?.uri||'');if(/(?:video|clip)-?\d+_\d+|vkvideo\.ru\/(?:video|watch|record)/i.test(page))score+=6;else if(/live\.vkvideo\.ru/i.test(page))score+=2;const th=String(v.thumbnail||'');if(th){if(/\/channel\/.*\/cover/i.test(th)||/preview/i.test(th))score+=5;else if(/\/user\/.*\/avatar/i.test(th))score+=1;else score+=3}else score-=2;const txt=`${p?.text||''} ${p?.author?.handle||''} ${p?.author?.displayName||''} ${v?.alt||''}`.toLocaleLowerCase('fr');for(const t of qs)if(txt.includes(t))score+=2;return{p,score,i}});ranked.sort((a,b)=>b.score-a.score||a.i-b.i);const posts=ranked.map(x=>x.p);return{...result,posts,screening:{strategy:'keyword-visual-v1',before:input.length,after:posts.length}}
}
