export type BookItem={topicId:number;title:string;description:string;genres:string[];publication:string|null;tomes:string|null;origin:string|null;language:string|null;sourceUrl:string;integratedAt:string|null;integrationOrder:number;isCategory:boolean}

const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0 Safari/537.36'
const GROUP='203785966'
const TIMEOUT=9000

function decode(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\\u([0-9a-f]{4})/gi,(_,h)=>String.fromCharCode(parseInt(h,16))).replace(/\\x([0-9a-f]{2})/gi,(_,h)=>String.fromCharCode(parseInt(h,16))).replace(/\\u0026/g,'&').replace(/\\u002F/gi,'/').replace(/\\\//g,'/').replace(/\\n/g,' ').replace(/\\t/g,' ')}
function strip(v:string){return decode(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
async function fetchText(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),TIMEOUT);try{const r=await fetch(url,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml','accept-language':'fr-FR,fr;q=0.9,en;q=0.6'},redirect:'follow',cache:'no-store',signal:c.signal});if(!r.ok)return null;return await r.text()}catch{return null}finally{clearTimeout(t)}}
function field(desc:string,name:string,next:string[]){const stop=next.map(x=>`${x}\\s*:`).join('|');const re=new RegExp(`${name}\\s*:\\s*(.*?)(?=\\s+(?:${stop})|$)`,'i');const m=desc.match(re);return m?m[1].trim():null}
function cleanTitle(v:string){return strip(v).replace(/\s*[|–-]\s*Au Phil Des Bulles(?:\s*[-|]\s*VK)?\s*$/i,'').replace(/\s*[|–-]\s*VK\s*$/i,'').trim()}
function categoryTitle(title:string,desc:string){if(/Genre\s*:/i.test(desc))return false;return /^(?:TOUT EN BD|SCIENCE[- ]FICTION|ANTICIPATION|FANTASTIQUE|HEROIC FANTASY|HEROÏC FANTASY|HISTORIQUE|WESTERN|POLICIER|THRILLER|AVENTURE|HUMOUR|JEUNESSE|MANGA|COMICS|ROMAN GRAPHIQUE|ONE SHOT|AUTEURS?|DESSINATEURS?|SCÉNARISTES?)(?:\b|\s*[-–])/i.test(title)}
function makeItem(url:string,titleRaw:string,descRaw:string,pageAge:string|null):BookItem|null{const m=url.match(/topic-203785966_(\d+)/);if(!m)return null;const topicId=Number(m[1]);const title=cleanTitle(titleRaw);if(!title)return null;const description=strip(descRaw);const genre=field(description,'Genre',['Parution','Tomes','Origine','Langue']);const publication=field(description,'Parution',['Tomes','Origine','Langue']);const tomes=field(description,'Tomes',['Origine','Langue']);const origin=field(description,'Origine',['Langue']);const language=field(description,'Langue',[]);let integratedAt:string|null=null;if(pageAge){const n=Number(pageAge);if(Number.isFinite(n)&&n>1_400_000_000&&n<4_000_000_000)integratedAt=new Date(n*1000).toISOString();else if(!Number.isNaN(Date.parse(pageAge)))integratedAt=new Date(pageAge).toISOString()}return{topicId,title,description,genres:genre?genre.split(/[,;/]+/).map(x=>x.trim()).filter(Boolean):[],publication,tomes,origin,language,sourceUrl:`https://vk.com/topic-203785966_${topicId}`,integratedAt,integrationOrder:topicId,isCategory:categoryTitle(title,description)}}
function parsePage(html:string){const text=decode(html);const found=new Map<number,BookItem>();const add=(url:string,title:string,desc:string,pageAge:string|null)=>{const item=makeItem(url,title,desc,pageAge);if(item&&!found.has(item.topicId))found.set(item.topicId,item)}
 for(const m of text.matchAll(/url:\s*["'](https?:\/\/(?:m\.)?vk\.com\/topic-203785966_\d+[^"']*)["']/gi)){const idx=m.index||0;const before=text.slice(Math.max(0,idx-900),idx);const after=text.slice(idx,idx+1800);const tm=[...before.matchAll(/title:\s*["']([^"']+)["']/gi)].pop();const dm=after.match(/description:\s*["']([^"']*)["']/i);const pm=after.match(/page_age:\s*(?:["']([^"']+)["']|(\d{9,13}))/i);add(m[1],tm?.[1]||'',dm?.[1]||'',pm?.[1]||pm?.[2]||null)}
 for(const m of text.matchAll(/<a\b[^>]*href=["']([^"']*topic-203785966_\d+[^"']*)["'][^>]*>([\s\S]*?)<\/a>/gi)){const idx=m.index||0;const around=text.slice(idx,idx+1500);add(new URL(decode(m[1]),'https://vk.com').toString(),m[2],strip(around),null)}
 return [...found.values()]}
function urls(page:number){const first=1+Math.max(0,page)*10;const offset=Math.max(0,page);const queries=[`site:vk.com/topic-203785966_ \"Au Phil Des Bulles\"`,`site:vk.com/topic-203785966_ \"Au Phil Des Bulles\" \"Genre\"`,`site:vk.com/topic-203785966_ \"Au Phil Des Bulles\" \"Langue\"`];return queries.flatMap(q=>[`https://search.brave.com/search?q=${encodeURIComponent(q)}&source=web&offset=${offset}`,`https://www.bing.com/search?q=${encodeURIComponent(q)}&count=20&first=${first}&adlt=off`,`https://yandex.com/search/?text=${encodeURIComponent(q)}&p=${offset}`])}
export async function booksPage(page=0){const pages=(await Promise.all(urls(page).map(fetchText))).filter(Boolean) as string[];const map=new Map<number,BookItem>();for(const html of pages)for(const item of parsePage(html)){const old=map.get(item.topicId);if(!old||item.description.length>old.description.length)map.set(item.topicId,item)}const all=[...map.values()].sort((a,b)=>(b.integratedAt?Date.parse(b.integratedAt):b.integrationOrder)-(a.integratedAt?Date.parse(a.integratedAt):a.integrationOrder));const categories=[...new Set(all.filter(x=>x.isCategory).map(x=>x.title).concat(all.flatMap(x=>x.genres)))].sort((a,b)=>a.localeCompare(b,'fr'));const books=all.filter(x=>!x.isCategory);return{books,categories,sourcePages:pages.length,nextPage:books.length||all.length?page+1:null}}
