import {NextRequest,NextResponse} from 'next/server'

const UA='Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/139.0 Safari/537.36'
function dec(v:string){return v.replace(/&amp;/g,'&').replace(/&quot;/g,'"').replace(/&#39;/g,"'").replace(/\\u0026/g,'&').replace(/\\u002F/gi,'/').replace(/\\\//g,'/')}
function strip(v:string){return dec(v).replace(/<script[\s\S]*?<\/script>/gi,' ').replace(/<style[\s\S]*?<\/style>/gi,' ').replace(/<[^>]+>/g,' ').replace(/\s+/g,' ').trim()}
async function get(url:string){const c=new AbortController();const t=setTimeout(()=>c.abort(),9000);try{const r=await fetch(url,{headers:{'user-agent':UA,'accept':'text/html,application/xhtml+xml','accept-language':'fr-FR,fr;q=0.9,en;q=0.6'},redirect:'follow',cache:'no-store',signal:c.signal});return{status:r.status,url:r.url,html:r.ok?await r.text():''}}catch{return{status:0,url,html:''}}finally{clearTimeout(t)}}
function title(h:string){const m=h.match(/<meta[^>]+property=["']og:title["'][^>]+content=["']([^"']+)["']/i)||h.match(/<title[^>]*>([\s\S]*?)<\/title>/i)||h.match(/<h1[^>]*>([\s\S]*?)<\/h1>/i);return m?strip(m[1]):''}
function meta(h:string,k:string){for(const tag of h.match(/<meta\b[^>]*>/gi)||[]){const p=(tag.match(/(?:property|name)=["']([^"']+)["']/i)||[])[1];const c=(tag.match(/content=["']([^"']+)["']/i)||[])[1];if(p?.toLowerCase()===k.toLowerCase()&&c)return strip(c)}return''}
export async function GET(req:NextRequest){const id=(req.nextUrl.searchParams.get('id')||'47976262').replace(/\D/g,'');if(!id)return NextResponse.json({error:'id'});const urls=[`https://vk.com/topic-203785966_${id}`,`https://m.vk.com/topic-203785966_${id}`];const pages=await Promise.all(urls.map(get));const out=pages.map(p=>{const h=dec(p.html);const ts=[...new Set([...h.matchAll(/(?<!\d)(1[4-9]\d{8}|20\d{8}|1\d{12})(?!\d)/g)].map(x=>x[1]))].slice(0,40);const hrefs=[...h.matchAll(/href=["']([^"']+)["']/gi)].map(x=>dec(x[1])).filter(x=>/\.pdf(?:$|[?#])|(?:vk\.com\/doc|docs?\.|\/doc-?\d+_\d+)/i.test(x)).slice(0,20);return{status:p.status,url:p.url,title:title(h),description:meta(h,'og:description')||meta(h,'description'),text:strip(h).slice(0,3500),timestamps:ts,docCount:hrefs.length,docSamples:hrefs.map(x=>{try{const u=new URL(x,p.url);return{host:u.hostname,path:u.pathname.slice(0,120)}}catch{return{host:'',path:x.slice(0,120)}}})}});return NextResponse.json({groupId:203785966,topicId:id,pages:out},{headers:{'Cache-Control':'no-store'}})}
